Repository privacy-scaling-explorations/sonobe, pull requests merged in 2024-12, with the labels that each got.

#178 docs fix spelling issues
  cli/README.md
Labels: typos

#183 reduce HyperNova proving time, reduce computation in Nova&Mova compute_T method
  benches/hypernova.rs
  benches/protogalaxy.rs
  folding-schemes/src/folding/hypernova/circuits.rs
  folding-schemes/src/folding/hypernova/mod.rs
  folding-schemes/src/folding/nova/nifs/mova.rs
  folding-schemes/src/folding/nova/nifs/nova.rs
Labels: optimization

#184 Reduce time for native computation in `prove_step`
  examples/external_inputs.rs
  examples/full_flow.rs
  examples/multi_inputs.rs
  examples/sha256.rs
  experimental-frontends/src/circom/mod.rs
  experimental-frontends/src/noir/mod.rs
  experimental-frontends/src/noname/mod.rs
  folding-schemes/src/arith/r1cs/circuits.rs
  folding-schemes/src/folding/circuits/cyclefold.rs
  folding-schemes/src/folding/hypernova/circuits.rs
  folding-schemes/src/folding/hypernova/mod.rs
  folding-schemes/src/folding/nova/circuits.rs
  folding-schemes/src/folding/nova/mod.rs
  folding-schemes/src/folding/protogalaxy/circuits.rs
  folding-schemes/src/folding/protogalaxy/mod.rs
  folding-schemes/src/frontend/mod.rs
  folding-schemes/src/frontend/utils.rs
  solidity-verifiers/src/verifiers/nova_cyclefold.rs
Labels: optimization

#191 Update the FCircuit trait, so that it supports custom data structures for the external inputs.
  .gitignore
  benches/common.rs
  examples/circom_full_flow.rs
  examples/external_inputs.rs
  examples/full_flow.rs
  examples/multi_inputs.rs
  examples/noir_full_flow.rs
  examples/noname_full_flow.rs
  examples/sha256.rs
  experimental-frontends/src/circom/mod.rs
  experimental-frontends/src/lib.rs
  experimental-frontends/src/noir/mod.rs
  experimental-frontends/src/noname/mod.rs
  experimental-frontends/src/utils.rs
  folding-schemes/src/folding/circuits/nonnative/uint.rs
  folding-schemes/src/folding/hypernova/circuits.rs
  folding-schemes/src/folding/hypernova/decider_eth.rs
  folding-schemes/src/folding/hypernova/decider_eth_circuit.rs
  folding-schemes/src/folding/hypernova/mod.rs
  folding-schemes/src/folding/mod.rs
  folding-schemes/src/folding/nova/circuits.rs
  folding-schemes/src/folding/nova/decider.rs
  folding-schemes/src/folding/nova/decider_circuits.rs
  folding-schemes/src/folding/nova/decider_eth.rs
  folding-schemes/src/folding/nova/decider_eth_circuit.rs
  folding-schemes/src/folding/nova/mod.rs
  folding-schemes/src/folding/protogalaxy/circuits.rs
  folding-schemes/src/folding/protogalaxy/decider_eth.rs
  folding-schemes/src/folding/protogalaxy/decider_eth_circuit.rs
  folding-schemes/src/folding/protogalaxy/mod.rs
  folding-schemes/src/frontend/mod.rs
  folding-schemes/src/frontend/utils.rs
  folding-schemes/src/lib.rs
  solidity-verifiers/Cargo.toml
  solidity-verifiers/src/verifiers/nova_cyclefold.rs
Labels: frontend
